### ISSUE TITLE
63am vs 64am

### ISSUE THREAD

**Issue by saurabheights** [iccv2021-mmp/mmp-tracking-helper#3]
Dear authors,
 What is the difference between 63am vs 64am?

**Comment by iccv2021-mmp** [comment]
It just marks different data recording dates.

________________________________
From: Saurabh Khanduja ***@***.***>
Sent: Sunday, September 1, 2024 4:50 AM
To: iccv2021-mmp/mmp-tracking-helper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iccv2021-mmp/mmp-tracking-helper] 63am vs 64am (Issue #3)


Dear authors,
What is the difference between 63am vs 64am?

**Comment by saurabheights** [comment]
Thank you.
